import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#c4c7c8',
        'on-primary-fixed': '#1a1c1c',
        'inverse-surface': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'surface-container': '#201f1f',
        'primary': '#ffffff',
        'tertiary-fixed': '#e2e2e2',
        'deep-space': '#0A0A0A',
        'on-secondary-container': '#b7b5b4',
        'secondary-fixed': '#e5e2e1',
        'surface-dim': '#141313',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#454747',
        'surface-container-highest': '#353434',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'primary-fixed': '#e2e2e2',
        'on-secondary-fixed-variant': '#474746',
        'secondary': '#c8c6c5',
        'starlight-gray': '#333333',
        'on-secondary-fixed': '#1c1b1b',
        'error-container': '#93000a',
        'inverse-primary': '#5d5f5f',
        'tertiary-container': '#e2e2e2',
        'on-tertiary-container': '#636565',
        'tertiary': '#ffffff',
        'surface-tint': '#c6c6c7',
        'inverse-on-surface': '#313030',
        'on-primary-container': '#636565',
        'surface-container-low': '#1c1b1b',
        'secondary-container': '#474746',
        'on-tertiary-fixed-variant': '#454747',
        'surface-variant': '#353434',
        'surface': '#141313',
        'background': '#141313',
        'on-secondary': '#313030',
        'error': '#ffb4ab',
        'primary-fixed-dim': '#c6c6c7',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-primary': '#2f3131',
        'secondary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1a1c1c',
        'void-black': '#000000',
        'on-tertiary': '#2f3131',
        'surface-bright': '#3a3939',
        'primary-container': '#e2e2e2',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      spacing: {
        'void-xs': '0.5rem',
        'void-sm': '1rem',
        'void-md': '2rem',
        'void-lg': '4rem',
        'void-xl': '8rem',
        'gutter': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '5vw',
      },
      fontFamily: {
        'display': ['Bodoni Moda', 'Georgia', 'serif'],
        'body': ['Hanken Grotesk', 'Helvetica Neue', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['84px', { lineHeight: '90px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.15em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0.02em', fontWeight: '300' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.2em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
export default config
